CREATE TABLE `respuestas` (
	`id` int AUTO_INCREMENT NOT NULL,
	`edad` int,
	`provincia` varchar(100),
	`ccaa` varchar(100),
	`nacionalidad` varchar(100),
	`voto_generales` varchar(100),
	`voto_autonomicas` varchar(100),
	`voto_municipales` varchar(100),
	`voto_europeas` varchar(100),
	`nota_ejecutivo` int,
	`val_feijoo` int,
	`val_sanchez` int,
	`val_abascal` int,
	`val_alvise` int,
	`val_yolanda_diaz` int,
	`val_irene_montero` int,
	`val_ayuso` int,
	`val_buxade` int,
	`voto_asociacion_juvenil` varchar(255),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `respuestas_id` PRIMARY KEY(`id`)
);
